volumes:
  mariadb:

services:
  mariadb:
    image: mariadb:12
    environment:
      MARIADB_DATABASE: soc-local
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql:Z
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  soc-local:
    ports:
      - 4321:4321
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      DATABASE_URL: 'mysql://root:root@mariadb:3306/soc-local'
