on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          check-latest: true
          cache: 'yarn'
      - run: |
          yarn build
