name: Build & Publish development image

on:
  workflow_call:

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create new tag from existing image
        run: |
          echo ${{github.token}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag  ghcr.io/${{ github.repository }}:production \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy production image
    needs: publish-prod
    secrets: inherit
    with:
      environment: production

  push-prod:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v6
      - name: Push development to production branch
        run: |
          git config push.default nothing
          git fetch origin production
          git push -f origin development:production
