name: Dev push

on:
  push:
    branches:
      - development

permissions:
  packages: write
  contents: write

jobs:
  pipeline-dev:
    uses: ./.github/workflows/pipeline-dev.yaml
    secrets: inherit

  pipeline-prod:
    needs: pipeline-dev
    uses: ./.github/workflows/pipeline-prod.yaml
    secrets: inherit
