name: Prod pipeline

on:
  workflow_call:

jobs:
  merge-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Merge development -> production
        run: |
          git config user.name ${{ github.actor }}
          git fetch origin production
          git checkout production
          git merge --no-commit --allow-unrelated-histories development 
          git push

      - name: Create new tag from existing image
        run: |
          echo ${{github.token}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag  ghcr.io/${{ github.repository }}:production \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    needs: merge-to-prod
    secrets: inherit
    with:
      environment: production
