name: Dev pipeline
on:
  workflow_call:

jobs:
  build-publish-dev:
    uses: ./.github/workflows/build-publish.yaml
    name: Build & publish Dev
    secrets: inherit
    permissions:
      packages: write
    with:
      environment: development

  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy Dev
    needs: build-publish-dev
    secrets: inherit
    with:
      environment: development
