name: Dev push

on:
  push:
    branches:
      - development

permissions:
  packages: write
  contents: write

jobs:
  build-publish-dev:
    uses: ./.github/workflows/build-publish.yaml
    name: Build & publish development image
    secrets: inherit
    permissions:
      packages: write
    with:
      environment: development

  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy development image
    needs: build-publish-dev
    secrets: inherit
    with:
      environment: development

  build-prod:
    uses: ./.github/workflows/build-publish-prod.yaml
    needs: deploy-dev
    secrets: inherit
