name: Dev push

on:
  push:
    branches:
      - development

permissions:
  packages: write
  contents: write

jobs:
  build-publish-dev:
    uses: ./.github/workflows/build-publish.yaml
    name: Build & publish development image
    secrets: inherit
    permissions:
      packages: write
    with:
      environment: dev-build

  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy development image
    needs: build-publish-dev
    secrets: inherit
    with:
      environment: development

  build-publish-prod:
    uses: ./.github/workflows/build-publish.yaml
    name: Build & publish production image
    secrets: inherit
    needs: deploy-dev
    permissions:
      packages: write
    with:
      environment: prod-build

  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    name: Deploy production image
    needs: build-publish-prod
    secrets: inherit
    with:
      environment: production

  push-prod:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v6
      - name: Push development to production branch
        run: |
          git config push.default nothing
          git fetch origin production
          git push -f origin development:production
